/**
 * ﻿Copyright Ministère des Affaires étrangères et du Développement international , 22 avril 2015
 * https://adullact.net/projects/hornet/
 *
 *
 * Ce logiciel est un programme informatique servant à faciliter la création
 *  d'applications Web accessibles conforémement au RGAA et performantes.
 *
 * Ce logiciel est régi par la licence CeCILL v2.1 soumise au droit français et
 * respectant les principes de diffusion des logiciels libres. Vous pouvez
 * utiliser, modifier et/ou redistribuer ce programme sous les conditions
 * de la licence CeCILL telle que diffusée par le CEA, le CNRS et l'INRIA
 * sur le site "http://www.cecill.info".
 *
 * En contrepartie de l'accessibilité au code source et des droits de copie,
 * de modification et de redistribution accordés par cette licence, il n'est
 * offert aux utilisateurs qu'une garantie limitée.  Pour les mêmes raisons,
 * seule une responsabilité restreinte pèse sur l'auteur du programme,  le
 * titulaire des droits patrimoniaux et les concédants successifs.
 *
 * A cet égard  l'attention de l'utilisateur est attirée sur les risques
 * associés au chargement,  à l'utilisation,  à la modification et/ou au
 * développement et à la reproduction du logiciel par l'utilisateur étant
 * donné sa spécificité de logiciel libre, qui peut le rendre complexe à
 * manipuler et qui le réserve donc à des développeurs et des professionnels
 * avertis possédant  des  connaissances  informatiques approfondies.  Les
 * utilisateurs sont donc invités à charger  et  tester  l'adéquation  du
 * logiciel à leurs besoins dans des conditions permettant d'assurer la
 * sécurité de leurs systèmes et ou de leurs données et, plus généralement,
 * à l'utiliser et l'exploiter dans les mêmes conditions de sécurité.
 *
 * Le fait que vous puissiez accéder à cet en-tête signifie que vous avez
 * pris connaissance de la licence CeCILL, et que vous en avez accepté les
 * termes.
 */
package fr.gouv.diplomatie.applitutoriel.ws.hello;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated source version: 2.1
 *
 */
@WebServiceClient(name = "HelloService",
            targetNamespace = "http://hello.ws.bouchonwebservice.hornet.diplomatie.gouv.fr/",
            wsdlLocation = "HelloService.wsdl")
public class HelloService extends Service {

    private final static URL HELLOSERVICE_WSDL_LOCATION;

    private final static Logger logger = LoggerFactory.getLogger(HelloService.class.getName());

    static {
        final URL url =
                    HelloService.class
                                .getResource("/fr/gouv/diplomatie/bouchonwebservice/wsdl/HelloService.wsdl");
        HELLOSERVICE_WSDL_LOCATION = url;
    }

    public HelloService(
                final URL wsdlLocation, final QName serviceName) {

        super(wsdlLocation, serviceName);
    }

    public HelloService() {

        super(HELLOSERVICE_WSDL_LOCATION, new QName(
                    "http://hello.ws.bouchonwebservice.hornet.diplomatie.gouv.fr/", "HelloService"));
    }

    /**
     *
     * @return returns IHelloService
     */
    @WebEndpoint(name = "HelloServicePort")
    public IHelloService getHelloServicePort() {

        return super.getPort(new QName("http://hello.ws.bouchonwebservice.hornet.diplomatie.gouv.fr/",
                    "HelloServicePort"), IHelloService.class);
    }

    /**
     *
     * @param features
     *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported
     *            features not in the <code>features</code> parameter will have their default values.
     * @return returns IHelloService
     */
    @WebEndpoint(name = "HelloServicePort")
    public IHelloService getHelloServicePort(final WebServiceFeature... features) {

        return super.getPort(new QName("http://hello.ws.bouchonwebservice.hornet.diplomatie.gouv.fr/",
                    "HelloServicePort"), IHelloService.class, features);
    }

}
